#  SET DATABASE CRITERIA
#  =====================

development:
  adapter: sqlite3
  database: ../db.sqlite3

production:
  adapter: mysql2
  database: heroku_05d4854da3a4a42
  username: b5e871bd510240
  password: ff0c2bbe
  host: mysql2://us-cdbr-iron-east-04.cleardb.net/heroku_05d4854da3a4a42?reconnect=true
