#  SET DATABASE CRITERIA
#  =====================

development:
  adapter: postgresql
  database: 'wuvrdb'
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: 'wuvrdb'
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: 'wuvrdb'
  pool: 5
  timeout: 5000
